"""Emit a PEP 561 stub package describing a Skaal app (ADR 028 §6.6.1).

The emitter walks an `App`'s `InferredPlan`, groups resources by kind, and
writes one `.pyi` file per kind plus an `__init__.pyi` index, a `py.typed`
marker, and a `_manifest.json` metadata file. Stub bodies are typed
*declarations only* — no runtime code is emitted.

Consuming projects add the output directory to their `pyrightconfig.json`
(or set it as a stubs path in `pyproject.toml`) and get LSP completion
for every covered symbol.
"""

from __future__ import annotations

import importlib
import inspect
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from skaal.inference.model import InferredPlan, InferredResource, ResourceKind
from skaal.stubs.manifest import StubManifest, StubResourceRef

if TYPE_CHECKING:
    from skaal.app import App


_STUB_HEADER = (
    "# Auto-generated by `skaal stubs` (ADR 028 §6.6.1).\n"
    "# Do not edit by hand. Re-run the CLI to regenerate.\n"
    "from __future__ import annotations\n\n"
)

_KIND_FILE: dict[ResourceKind, str] = {
    ResourceKind.STORE: "stores.pyi",
    ResourceKind.RELATIONAL: "relational.pyi",
    ResourceKind.BLOB: "blobs.pyi",
    ResourceKind.CHANNEL: "channels.pyi",
    ResourceKind.FUNCTION: "functions.pyi",
}


class StubEmitError(RuntimeError):
    """Raised when stub emission cannot proceed.

    The CLI wraps this in a typer-formatted error; programmatic callers
    can catch it directly.
    """


def discover_app(source: Path) -> App:
    """Resolve the `App` instance hosted by a source path.

    `source` may be a directory (added to `sys.path` and walked for a
    package containing an `app: App` attribute) or a `module:attribute`
    string (parsed and resolved via `importlib.import_module`).

    Args:
        source: Filesystem path to an importable Python package, or a
            `module:attribute` reference resolvable on the current
            `sys.path`.

    Returns:
        The resolved `App` instance.

    Raises:
        StubEmitError: If no `App` is discoverable, or if more than one
            is present without an explicit `module:attribute` selector.
    """
    from skaal.app import App

    resolved = _resolve_source(source)
    if isinstance(resolved, App):
        return resolved
    raise StubEmitError(
        f"`{source}` did not resolve to a `skaal.App` instance "
        f"(got `{type(resolved).__name__}` instead)."
    )


def _resolve_source(source: Path) -> object:
    """Return the value the user pointed `--from` at.

    The form `module:attribute` short-circuits filesystem discovery and
    is the recommended form for libraries that ship multiple apps. The
    filesystem form is the convenience for one-package-one-app projects.
    """
    raw = str(source)
    if ":" in raw and not Path(raw).exists():
        module_name, _, attr = raw.partition(":")
        return _import_attribute(module_name, attr)

    path = Path(raw).resolve()
    if not path.exists():
        raise StubEmitError(f"`{source}` does not exist on disk.")

    parent = path.parent
    package = path.stem if path.is_file() else path.name
    if str(parent) not in sys.path:
        sys.path.insert(0, str(parent))

    try:
        module = importlib.import_module(package)
    except ImportError as exc:
        raise StubEmitError(f"Could not import `{package}` from `{parent}`: {exc}") from exc

    app_instance = _find_single_app(module)
    if app_instance is None:
        raise StubEmitError(
            f"No `skaal.App` instance discoverable in `{package}`. "
            "Use `--from <module>:<attribute>` to point at a specific app."
        )
    return app_instance


def _import_attribute(module_name: str, attribute: str) -> object:
    try:
        module = importlib.import_module(module_name)
    except ImportError as exc:
        raise StubEmitError(f"Could not import `{module_name}`: {exc}") from exc
    if not hasattr(module, attribute):
        raise StubEmitError(f"`{module_name}` has no attribute `{attribute}`.")
    return getattr(module, attribute)


def _find_single_app(module: object) -> App | None:
    from skaal.app import App

    candidates: list[App] = []
    seen: set[int] = set()
    for name in dir(module):
        if name.startswith("_"):
            continue
        value = getattr(module, name, None)
        if isinstance(value, App) and id(value) not in seen:
            candidates.append(value)
            seen.add(id(value))

    if not candidates:
        return None
    if len(candidates) > 1:
        names = ", ".join(sorted(getattr(a, "name", "?") for a in candidates))
        raise StubEmitError(
            f"Multiple `skaal.App` instances found ({names}); "
            "disambiguate with `--from <module>:<attribute>`."
        )
    return candidates[0]


def emit_stubs(
    *,
    app: App,
    out_dir: Path,
    package_name: str,
) -> Path:
    """Emit a PEP 561 stub package describing `app` to `out_dir`.

    Args:
        app: The Skaal application whose surface is being stubbed.
        out_dir: Destination directory. Must be empty *or* an existing
            stub package whose manifest reports the same `package_name`.
        package_name: The Python package name consumers will import as
            (`from <package_name> import Customers`).

    Returns:
        The resolved `out_dir`, after the package has been written.

    Raises:
        StubEmitError: If `out_dir` is occupied by an unrelated package,
            or if `package_name` is not a valid Python identifier.
    """
    if not package_name.isidentifier():
        raise StubEmitError(f"`{package_name}` is not a valid Python package name.")

    out_dir = out_dir.resolve()
    _prepare_out_dir(out_dir, package_name)

    plan = app.infer()
    resources_by_kind = _group_by_kind(plan)

    (out_dir / "py.typed").write_text("", encoding="utf-8")
    init_path = out_dir / "__init__.pyi"
    init_path.write_text(_render_init(resources_by_kind), encoding="utf-8")

    for kind, resources in resources_by_kind.items():
        filename = _KIND_FILE.get(kind)
        if filename is None:
            continue
        body = _render_kind(kind, resources)
        (out_dir / filename).write_text(body, encoding="utf-8")

    manifest = _build_manifest(plan, package_name)
    (out_dir / "_manifest.json").write_text(manifest.to_json(), encoding="utf-8")

    return out_dir


def _prepare_out_dir(out_dir: Path, package_name: str) -> None:
    """Create or validate the target stub directory.

    Re-running with matching `package_name` is idempotent; mismatched
    `package_name` is rejected so a fat-fingered second invocation does
    not silently corrupt an existing stub package.
    """
    if out_dir.exists():
        manifest_path = out_dir / "_manifest.json"
        if manifest_path.exists():
            try:
                existing = StubManifest.from_json(manifest_path.read_text(encoding="utf-8"))
            except Exception as exc:
                raise StubEmitError(
                    f"`{out_dir}` already contains a `_manifest.json` that does not parse: {exc}"
                ) from exc
            if existing.package_name != package_name:
                raise StubEmitError(
                    f"`{out_dir}` already hosts a stub package named "
                    f"`{existing.package_name}`; refusing to overwrite with `{package_name}`."
                )
            _clean_generated(out_dir)
            return
        if any(out_dir.iterdir()):
            raise StubEmitError(
                f"`{out_dir}` is not empty and does not look like an existing stub package."
            )
    else:
        out_dir.mkdir(parents=True)


def _clean_generated(out_dir: Path) -> None:
    """Remove every file the emitter is about to (re)write.

    User-added files in the directory are preserved — the cleaner only
    touches names the emitter owns (`*.pyi`, `py.typed`, `_manifest.json`).
    """
    for path in out_dir.iterdir():
        if path.name == "_manifest.json" or path.name == "py.typed" or path.suffix == ".pyi":
            path.unlink()


def _group_by_kind(
    plan: InferredPlan,
) -> dict[ResourceKind, list[InferredResource]]:
    """Bucket the plan's resources by their `ResourceKind`."""
    grouped: dict[ResourceKind, list[InferredResource]] = {}
    for res in plan.resources:
        grouped.setdefault(res.kind, []).append(res)
    for bucket in grouped.values():
        bucket.sort(key=lambda r: r.id)
    return grouped


def _build_manifest(plan: InferredPlan, package_name: str) -> StubManifest:
    from skaal import __version__

    refs = tuple(
        StubResourceRef(
            id=res.id,
            kind=res.kind.value,
            module=res.source.module,
            qualname=res.source.qualname,
        )
        for res in plan.resources
    )
    first_module = plan.resources[0].source.module if plan.resources else ""
    return StubManifest(
        package_name=package_name,
        source_module=first_module,
        source_app=plan.app,
        app_fingerprint=plan.fingerprint or None,
        skaal_version=__version__,
        generated_at=datetime.now(UTC),
        resources=refs,
    )


def _render_init(
    resources_by_kind: dict[ResourceKind, list[InferredResource]],
) -> str:
    """Render `__init__.pyi` re-exporting every covered symbol."""
    lines: list[str] = [_STUB_HEADER.rstrip("\n"), ""]
    all_names: list[str] = []
    for kind, resources in resources_by_kind.items():
        filename = _KIND_FILE.get(kind)
        if filename is None or not resources:
            continue
        module = filename.removesuffix(".pyi")
        names = sorted({_local_symbol(res) for res in resources})
        if not names:
            continue
        joined = ", ".join(names)
        lines.append(f"from .{module} import {joined}")
        all_names.extend(names)
    lines.append("")
    if all_names:
        all_list = ", ".join(f'"{name}"' for name in sorted(set(all_names)))
        lines.append(f"__all__ = [{all_list}]")
    lines.append("")
    return "\n".join(lines)


def _render_kind(kind: ResourceKind, resources: list[InferredResource]) -> str:
    """Render the `.pyi` body for one resource kind."""
    body = [_STUB_HEADER.rstrip("\n"), ""]
    imports = _imports_for(kind, resources)
    if imports:
        body.extend(imports)
        body.append("")
    for res in resources:
        body.append(_render_resource(kind, res))
        body.append("")
    return "\n".join(body).rstrip() + "\n"


def _imports_for(kind: ResourceKind, resources: list[InferredResource]) -> list[str]:
    """Compute the `from skaal import …` line for a kind's stub file."""
    if kind is ResourceKind.STORE:
        return ["from skaal import Store"]
    if kind is ResourceKind.RELATIONAL:
        return ["from skaal import Relational"]
    if kind is ResourceKind.BLOB:
        return ["from skaal import BlobStore"]
    if kind is ResourceKind.CHANNEL:
        return ["from skaal import Channel"]
    if kind is ResourceKind.FUNCTION:
        return ["from typing import Any"]
    return []


def _local_symbol(res: InferredResource) -> str:
    """Return the public name a stub consumer imports the resource as.

    For most resources this is `qualname`'s last segment. Free functions
    keep their bare name; classes nested inside another class are stubbed
    under the outer class's name.
    """
    return res.source.qualname.rpartition(".")[-1]


def _render_resource(kind: ResourceKind, res: InferredResource) -> str:
    name = _local_symbol(res)
    if kind is ResourceKind.STORE:
        return f"class {name}(Store): ..."
    if kind is ResourceKind.RELATIONAL:
        return f"class {name}(Relational): ..."
    if kind is ResourceKind.BLOB:
        return f"class {name}(BlobStore): ..."
    if kind is ResourceKind.CHANNEL:
        return f"class {name}(Channel): ..."
    if kind is ResourceKind.FUNCTION:
        return _render_function(res, name)
    return f"# unsupported kind: {kind.value}"


def _render_function(res: InferredResource, name: str) -> str:
    """Render a `def name(...) -> Any: ...` line for an inferred function.

    The signature is recovered via `inspect.signature` against the live
    callable when reachable; when the resource is reachable only by id
    (e.g., the consumer is generating stubs from a `BoundPlan` checked
    in to git), the emitter falls back to a `*args: Any, **kwargs: Any`
    signature.
    """
    fn = _resolve_callable(res)
    if not callable(fn):
        return f"def {name}(*args: Any, **kwargs: Any) -> Any: ..."
    try:
        sig = inspect.signature(fn)
    except (TypeError, ValueError):
        return f"def {name}(*args: Any, **kwargs: Any) -> Any: ..."
    return f"def {name}{sig}: ..."


def _resolve_callable(res: InferredResource) -> object | None:
    """Best-effort live-import of the callable behind a `FUNCTION` resource."""
    try:
        module = importlib.import_module(res.source.module)
    except ImportError:
        return None
    target: object = module
    for part in res.source.qualname.split("."):
        target = getattr(target, part, None)
        if target is None:
            return None
    return target
