"""skaal.types — all constraint and schema types.

Re-exports everything so existing code using ``from skaal.types import X``
continues to work without change.
"""

from importlib import import_module

from skaal.types.blob import BlobObject
from skaal.types.catalog import CatalogRaw, CatalogSource
from skaal.types.cli import ChangeBatch, ChangeStream, ChildArgv, ReloadDirs, ReloadMode
from skaal.types.compute import (
    Bulkhead,
    CircuitBreaker,
    Compute,
    ComputeType,
    RateLimitPolicy,
    RetryPolicy,
    Scale,
    ScaleStrategy,
)
from skaal.types.constraints import (
    AccessPattern,
    Consistency,
    DecommissionPolicy,
    Durability,
    Latency,
    Persistent,
    Throughput,
)
from skaal.types.deploy import (
    AppLike,
    AppRefConfig,
    AuthConfig,
    BackendWiring,
    CloudRunEnvValueSource,
    CloudRunEnvVar,
    CloudRunSecretKeyRef,
    ComponentConfig,
    ComponentKind,
    ConfigOverrides,
    CronTriggerConfig,
    DeployMeta,
    DockerBuildConfig,
    DockerContainerProperties,
    DockerHealthcheck,
    DockerImageProperties,
    DockerLabel,
    DockerNetworkAttachment,
    DockerPortBinding,
    DockerVolumeMount,
    EveryTriggerConfig,
    ExternalComponentConfig,
    ExternalObservabilityConfig,
    ExternalQueueConfig,
    ExternalStorageConfig,
    GatewayConfig,
    LocalServiceSpec,
    PulumiPlugins,
    PulumiProviderPlugin,
    PulumiResource,
    PulumiResourceOptions,
    PulumiStack,
    RateLimitConfig,
    RouteSpec,
    ScheduleTriggerConfig,
    StackOutputs,
    StackProfile,
    TargetName,
)
from skaal.types.duration import TTL, Duration, Retention
from skaal.types.invoke import BeforeInvoke, InvokeContext, StreamFn
from skaal.types.job import JobHandle, JobResult, JobSpec, JobStatus
from skaal.types.observability import (
    EngineTelemetrySnapshot,
    HeaderMap,
    ReadinessState,
    TelemetryConfig,
    TelemetryExporter,
)
from skaal.types.patterns import (
    EventLogPatternConfig,
    EventLogPatternMetadata,
    EventLogStorageMetadata,
    OutboxChannelRef,
    OutboxDelivery,
    OutboxPatternConfig,
    OutboxPatternMetadata,
    PatternConfig,
    PatternMetadata,
    ProjectionDeadLetterRef,
    ProjectionDeadLetterSink,
    ProjectionFailureError,
    ProjectionFailurePayload,
    ProjectionHandler,
    ProjectionHandlerResult,
    ProjectionPatternConfig,
    ProjectionPatternMetadata,
    SagaPatternConfig,
    SagaPatternMetadata,
    SagaStepMetadata,
)
from skaal.types.protocols import (
    AsyncPublishRef,
    AsyncPublishTarget,
    SupportsAsyncAppend,
    SupportsAsyncSend,
)
from skaal.types.relational import (
    RelationalMigrationBackend,
    RelationalMigrationOp,
    RelationalMigrationPlan,
    RelationalMigrationStatus,
    RelationalMigrationStep,
    RelationalModelType,
    RelationalRevision,
    SupportsSqlalchemyDsn,
    SupportsSqlalchemyUrl,
)
from skaal.types.schema import apply_migrations, migrate_from
from skaal.types.secret import (
    AwsSecretsManagerClient,
    AwsSecretsManagerSession,
    AwsSecretValueResponse,
    GcpSecretManagerClient,
    GcpSecretPayload,
    GcpSecretVersionResponse,
    ResolvedSecret,
    SecretGrant,
    SecretProvider,
    SecretRef,
    SecretResolver,
    SecretSpec,
)
from skaal.types.solver import (
    CandidateReport,
    Diagnosis,
    RelaxSuggestion,
    ResourceKind,
    Violation,
)
from skaal.types.storage import Page, SecondaryIndex

__all__ = [
    # constraints
    "AccessPattern",
    "Consistency",
    "DecommissionPolicy",
    "Durability",
    "Latency",
    "Persistent",
    "Throughput",
    "Duration",
    "Retention",
    "TTL",
    # blob
    "BlobObject",
    # catalog (pre-validation layer; see skaal.catalog.models for the typed Catalog)
    "CatalogRaw",
    "CatalogSource",
    # cli
    "ChangeBatch",
    "ChangeStream",
    "ChildArgv",
    "ReloadDirs",
    "ReloadMode",
    # deploy
    "AppRefConfig",
    "AppLike",
    "AuthConfig",
    "BackendWiring",
    "ComponentConfig",
    "ComponentKind",
    "CronTriggerConfig",
    "CloudRunEnvValueSource",
    "CloudRunEnvVar",
    "CloudRunSecretKeyRef",
    "ConfigOverrides",
    "DeployMeta",
    "DockerBuildConfig",
    "DockerContainerProperties",
    "DockerHealthcheck",
    "DockerImageProperties",
    "DockerLabel",
    "DockerNetworkAttachment",
    "DockerPortBinding",
    "DockerVolumeMount",
    "EveryTriggerConfig",
    "ExternalComponentConfig",
    "ExternalObservabilityConfig",
    "ExternalQueueConfig",
    "ExternalStorageConfig",
    "GatewayConfig",
    "LocalServiceSpec",
    "PulumiPlugins",
    "PulumiProviderPlugin",
    "PulumiResource",
    "PulumiResourceOptions",
    "PulumiStack",
    "RateLimitConfig",
    "RouteSpec",
    "ScheduleTriggerConfig",
    "StackOutputs",
    "StackProfile",
    "TargetName",
    "TelemetryConfig",
    "TelemetryExporter",
    "EngineTelemetrySnapshot",
    "ReadinessState",
    "HeaderMap",
    "JobHandle",
    "JobResult",
    "JobSpec",
    "JobStatus",
    # patterns
    "AsyncPublishRef",
    "AsyncPublishTarget",
    "EventLogPatternConfig",
    "EventLogPatternMetadata",
    "EventLogStorageMetadata",
    "OutboxChannelRef",
    "OutboxPatternConfig",
    "OutboxDelivery",
    "OutboxPatternMetadata",
    "PatternConfig",
    "PatternMetadata",
    "ProjectionDeadLetterRef",
    "ProjectionDeadLetterSink",
    "ProjectionFailureError",
    "ProjectionFailurePayload",
    "ProjectionHandler",
    "ProjectionHandlerResult",
    "ProjectionPatternConfig",
    "ProjectionPatternMetadata",
    "SagaPatternConfig",
    "SagaPatternMetadata",
    "SagaStepMetadata",
    # invoke
    "BeforeInvoke",
    "InvokeContext",
    "StreamFn",
    # solver / diagnostics
    "CandidateReport",
    "Diagnosis",
    "RelaxSuggestion",
    "ResourceKind",
    "Violation",
    # secrets
    "ResolvedSecret",
    "AwsSecretValueResponse",
    "AwsSecretsManagerClient",
    "AwsSecretsManagerSession",
    "GcpSecretManagerClient",
    "GcpSecretPayload",
    "GcpSecretVersionResponse",
    "SecretGrant",
    "SecretProvider",
    "SecretRef",
    "SecretResolver",
    "SecretSpec",
    # storage
    "Page",
    "SecondaryIndex",
    # relational migrations
    "RelationalMigrationOp",
    "RelationalMigrationBackend",
    "RelationalMigrationPlan",
    "RelationalMigrationStatus",
    "RelationalMigrationStep",
    "RelationalModelType",
    "RelationalRevision",
    "SupportsSqlalchemyDsn",
    "SupportsSqlalchemyUrl",
    # compute
    "Bulkhead",
    "CircuitBreaker",
    "Compute",
    "ComputeType",
    "RateLimitPolicy",
    "RetryPolicy",
    "Scale",
    "ScaleStrategy",
    # schema
    "apply_migrations",
    "migrate_from",
    # runtime
    "AgentsService",
    "AsyncClosable",
    "BackendOverrides",
    "ConstructorKwargs",
    "DispatchResult",
    "MeshClient",
    "RuntimeObserver",
    "RuntimeApp",
    "RuntimeCallable",
    "RuntimeInstance",
    "RuntimeInvoker",
    "RuntimeKwargs",
    "RuntimeMode",
    "RuntimePayload",
    "RuntimePlanSource",
    "RuntimeServices",
    "RuntimeWireParams",
    "StateService",
    "StorageClassMap",
    "StorageKindName",
    "SupportsAsyncAppend",
    "SupportsAsyncSend",
]

_LAZY_RUNTIME_EXPORTS = {
    "AgentsService",
    "AsyncClosable",
    "BackendOverrides",
    "ConstructorKwargs",
    "DispatchResult",
    "MeshClient",
    "RuntimeObserver",
    "RuntimeApp",
    "RuntimeCallable",
    "RuntimeInstance",
    "RuntimeInvoker",
    "RuntimeKwargs",
    "RuntimeMode",
    "RuntimePayload",
    "RuntimePlanSource",
    "RuntimeServices",
    "RuntimeWireParams",
    "StateService",
    "StorageClassMap",
    "StorageKindName",
}


def __getattr__(name: str) -> object:
    if name in _LAZY_RUNTIME_EXPORTS:
        module = import_module("skaal.types.runtime")
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
