"""skaal.types — all constraint and schema types.

Re-exports everything so existing code using ``from skaal.types import X``
continues to work without change.
"""

from importlib import import_module

from skaal.types.blob import BlobObject
from skaal.types.catalog import CatalogRaw, CatalogSource
from skaal.types.cli import ChangeBatch, ChangeStream, ChildArgv, ReloadDirs, ReloadMode
from skaal.types.compute import (
    Bulkhead,
    CircuitBreaker,
    Compute,
    ComputeType,
    RateLimitPolicy,
    RetryPolicy,
    Scale,
    ScaleStrategy,
)
from skaal.types.constraints import (
    AccessPattern,
    Consistency,
    DecommissionPolicy,
    Durability,
    Latency,
    Persistent,
    Throughput,
)
from skaal.types.deploy import (
    AppLike,
    AppRefConfig,
    AuthConfig,
    BackendWiring,
    CloudRunEnvValueSource,
    CloudRunEnvVar,
    CloudRunSecretKeyRef,
    ComponentConfig,
    ComponentKind,
    ConfigOverrides,
    CronTriggerConfig,
    DeployMeta,
    DockerBuildConfig,
    DockerContainerProperties,
    DockerHealthcheck,
    DockerImageProperties,
    DockerLabel,
    DockerNetworkAttachment,
    DockerPortBinding,
    DockerVolumeMount,
    EveryTriggerConfig,
    ExternalComponentConfig,
    ExternalObservabilityConfig,
    ExternalQueueConfig,
    ExternalStorageConfig,
    GatewayConfig,
    LocalServiceSpec,
    PulumiPlugins,
    PulumiProviderPlugin,
    PulumiResource,
    PulumiResourceOptions,
    PulumiStack,
    RateLimitConfig,
    RouteSpec,
    ScheduleTriggerConfig,
    StackOutputs,
    StackProfile,
    TargetName,
)
from skaal.types.duration import TTL, Duration, Retention
from skaal.types.invoke import BeforeInvoke, InvokeContext, StreamFn
from skaal.types.job import JobHandle, JobResult, JobSpec, JobStatus
from skaal.types.observability import (
    EngineTelemetrySnapshot,
    HeaderMap,
    ReadinessState,
    TelemetryConfig,
    TelemetryExporter,
)
from skaal.types.patterns import (
    EventLogPatternConfig,
    EventLogPatternMetadata,
    EventLogStorageMetadata,
    OutboxChannelRef,
    OutboxDelivery,
    OutboxPatternConfig,
    OutboxPatternMetadata,
    PatternConfig,
    PatternMetadata,
    ProjectionDeadLetterRef,
    ProjectionDeadLetterSink,
    ProjectionFailureError,
    ProjectionFailurePayload,
    ProjectionHandler,
    ProjectionHandlerResult,
    ProjectionPatternConfig,
    ProjectionPatternMetadata,
    SagaPatternConfig,
    SagaPatternMetadata,
    SagaStepMetadata,
)
from skaal.types.protocols import (
    AsyncPublishRef,
    AsyncPublishTarget,
    SupportsAsyncAppend,
    SupportsAsyncSend,
)
from skaal.types.relational import (
    RelationalMigrationBackend,
    RelationalMigrationOp,
    RelationalMigrationPlan,
    RelationalMigrationStatus,
    RelationalMigrationStep,
    RelationalModelType,
    RelationalRevision,
    SupportsSqlalchemyDsn,
    SupportsSqlalchemyUrl,
)
from skaal.types.schema import apply_migrations, migrate_from
from skaal.types.secret import (
    AwsSecretsManagerClient,
    AwsSecretsManagerSession,
    AwsSecretValueResponse,
    GcpSecretManagerClient,
    GcpSecretPayload,
    GcpSecretVersionResponse,
    ResolvedSecret,
    SecretGrant,
    SecretProvider,
    SecretRef,
    SecretResolver,
    SecretSpec,
)
from skaal.types.solver import (
    CandidateReport,
    Diagnosis,
    RelaxSuggestion,
    ResourceKind,
    Violation,
)
from skaal.types.storage import BackendIndexFields, CursorPayload, Page, SecondaryIndex

__all__ = [
    "TTL",
    "AccessPattern",
    "AgentsService",
    "AppLike",
    "AppRefConfig",
    "AsyncClosable",
    "AsyncPublishRef",
    "AsyncPublishTarget",
    "AuthConfig",
    "AwsSecretValueResponse",
    "AwsSecretsManagerClient",
    "AwsSecretsManagerSession",
    "BackendIndexFields",
    "BackendOverrides",
    "BackendWiring",
    "BeforeInvoke",
    "BlobObject",
    "Bulkhead",
    "CandidateReport",
    "CatalogRaw",
    "CatalogSource",
    "ChangeBatch",
    "ChangeStream",
    "ChildArgv",
    "CircuitBreaker",
    "CloudRunEnvValueSource",
    "CloudRunEnvVar",
    "CloudRunSecretKeyRef",
    "ComponentConfig",
    "ComponentKind",
    "Compute",
    "ComputeType",
    "ConfigOverrides",
    "Consistency",
    "ConstructorKwargs",
    "CronTriggerConfig",
    "CursorPayload",
    "DecommissionPolicy",
    "DeployMeta",
    "Diagnosis",
    "DispatchResult",
    "DockerBuildConfig",
    "DockerContainerProperties",
    "DockerHealthcheck",
    "DockerImageProperties",
    "DockerLabel",
    "DockerNetworkAttachment",
    "DockerPortBinding",
    "DockerVolumeMount",
    "Durability",
    "Duration",
    "EngineTelemetrySnapshot",
    "EventLogPatternConfig",
    "EventLogPatternMetadata",
    "EventLogStorageMetadata",
    "EveryTriggerConfig",
    "ExternalComponentConfig",
    "ExternalObservabilityConfig",
    "ExternalQueueConfig",
    "ExternalStorageConfig",
    "GatewayConfig",
    "GcpSecretManagerClient",
    "GcpSecretPayload",
    "GcpSecretVersionResponse",
    "HeaderMap",
    "InvokeContext",
    "JobHandle",
    "JobResult",
    "JobSpec",
    "JobStatus",
    "Latency",
    "LocalServiceSpec",
    "MeshClient",
    "OutboxChannelRef",
    "OutboxDelivery",
    "OutboxPatternConfig",
    "OutboxPatternMetadata",
    "Page",
    "PatternConfig",
    "PatternMetadata",
    "Persistent",
    "ProjectionDeadLetterRef",
    "ProjectionDeadLetterSink",
    "ProjectionFailureError",
    "ProjectionFailurePayload",
    "ProjectionHandler",
    "ProjectionHandlerResult",
    "ProjectionPatternConfig",
    "ProjectionPatternMetadata",
    "PulumiPlugins",
    "PulumiProviderPlugin",
    "PulumiResource",
    "PulumiResourceOptions",
    "PulumiStack",
    "RateLimitConfig",
    "RateLimitPolicy",
    "ReadinessState",
    "RelationalMigrationBackend",
    "RelationalMigrationOp",
    "RelationalMigrationPlan",
    "RelationalMigrationStatus",
    "RelationalMigrationStep",
    "RelationalModelType",
    "RelationalRevision",
    "RelaxSuggestion",
    "ReloadDirs",
    "ReloadMode",
    "ResolvedSecret",
    "ResourceKind",
    "Retention",
    "RetryPolicy",
    "RouteSpec",
    "RuntimeApp",
    "RuntimeCallable",
    "RuntimeInstance",
    "RuntimeInvoker",
    "RuntimeKwargs",
    "RuntimeMode",
    "RuntimeObserver",
    "RuntimePayload",
    "RuntimePlanSource",
    "RuntimeServices",
    "RuntimeWireParams",
    "SagaPatternConfig",
    "SagaPatternMetadata",
    "SagaStepMetadata",
    "Scale",
    "ScaleStrategy",
    "ScheduleTriggerConfig",
    "SecondaryIndex",
    "SecretGrant",
    "SecretProvider",
    "SecretRef",
    "SecretResolver",
    "SecretSpec",
    "StackOutputs",
    "StackProfile",
    "StateService",
    "StorageClassMap",
    "StorageKindName",
    "StreamFn",
    "SupportsAsyncAppend",
    "SupportsAsyncSend",
    "SupportsSqlalchemyDsn",
    "SupportsSqlalchemyUrl",
    "TargetName",
    "TelemetryConfig",
    "TelemetryExporter",
    "Throughput",
    "Violation",
    "apply_migrations",
    "migrate_from",
]

_LAZY_RUNTIME_EXPORTS = {
    "AgentsService",
    "AsyncClosable",
    "BackendOverrides",
    "ConstructorKwargs",
    "DispatchResult",
    "MeshClient",
    "RuntimeObserver",
    "RuntimeApp",
    "RuntimeCallable",
    "RuntimeInstance",
    "RuntimeInvoker",
    "RuntimeKwargs",
    "RuntimeMode",
    "RuntimePayload",
    "RuntimePlanSource",
    "RuntimeServices",
    "RuntimeWireParams",
    "StateService",
    "StorageClassMap",
    "StorageKindName",
}


def __getattr__(name: str) -> object:
    if name in _LAZY_RUNTIME_EXPORTS:
        module = import_module("skaal.types.runtime")
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
