"""
Generated by `skaal deploy`. Do not edit manually.
App: $app_name  Target: aws-jobs-worker
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

import $source_module as _user_module

$backend_imports
from skaal.runtime.local import LocalRuntime

_runtime = LocalRuntime(
    _user_module.$app_var,
    backend_overrides={
$backend_overrides
    },
)


async def _drain() -> dict[str, int]:
    max_bursts = max(1, int(os.environ.get("SKAAL_JOBS_WORKER_MAX_BURSTS", "5")))
    max_jobs = max(1, int(os.environ.get("SKAAL_JOBS_WORKER_MAX_JOBS", "10")))
    processed = 0
    for _ in range(max_bursts):
        drained = await _runtime.run_job_worker_burst(max_jobs=max_jobs)
        processed += drained
        if drained == 0:
            break
    return {"processed": processed}


def handler(event, context):
    del event, context
    return asyncio.run(_drain())
