"""AWS Lambda artifact generator — thin orchestrator over deploy/templates/aws/."""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Any

from skaal.deploy._render import _CodeWriter, render

if TYPE_CHECKING:
    from skaal.plan import PlanFile


# ── Wiring helpers (backend_imports / backend_overrides for templates) ─────────

def _build_wiring(plan: "PlanFile") -> tuple[str, str]:
    """
    Return (backend_imports, backend_overrides) template variables.

    Lambda uses DynamoDB for all storage classes — the backend name and table
    are determined at runtime via environment variables injected by the Pulumi
    stack.
    """
    import_lines: list[str] = []
    override_lines: list[str] = []

    if plan.storage:
        import_lines.append("from skaal.backends.dynamodb_backend import DynamoBackend")

    for qname, _spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        env_var = f"SKAAL_TABLE_{class_name.upper()}"
        override_lines.append(f'        "{class_name}": DynamoBackend(os.environ["{env_var}"]),')

    return "\n".join(import_lines), "\n".join(override_lines)


# ── Pulumi stack builder ───────────────────────────────────────────────────────

def _build_pulumi_main(app: Any, plan: "PlanFile") -> str:
    """Generate pulumi/__main__.py using _CodeWriter — no string-list hacks."""
    w = _CodeWriter()

    w.block(f"""\
        \"\"\"
        Pulumi stack generated by `skaal deploy`.
        App: {app.name}  Target: aws-lambda
        Do not edit manually — regenerate with `skaal deploy`.
        \"\"\"
        import pulumi
        import pulumi_aws as aws

        config = pulumi.Config()
        stack_name = pulumi.get_stack()
        app_name = "{app.name}"
    """)

    # ── DynamoDB tables ───────────────────────────────────────────────────────
    table_vars: dict[str, str] = {}  # class_name → resource variable name

    w.blank()
    w.line("# ── DynamoDB Tables " + "─" * 60)

    for qname, spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        var = f"table_{class_name.lower()}"
        table_vars[class_name] = var
        w.blank()
        w.block(f"""\
            {var} = aws.dynamodb.Table(
                "{class_name.lower()}-table",
                name=f"{{stack_name}}-{class_name.lower()}",
                hash_key="pk",
                billing_mode="PAY_PER_REQUEST",
                attributes=[aws.dynamodb.TableAttributeArgs(name="pk", type="S")],
                tags={{"skaal-app": app_name, "skaal-storage": "{qname}"}},
            )
        """)

    # ── IAM role ─────────────────────────────────────────────────────────────
    w.blank()
    w.line("# ── IAM Role for Lambda " + "─" * 56)
    w.block(f"""\
        lambda_role = aws.iam.Role(
            "skaal-lambda-role",
            name=f"{{stack_name}}-{app.name}-role",
            assume_role_policy={{
                "Version": "2012-10-17",
                "Statement": [{{
                    "Effect": "Allow",
                    "Principal": {{"Service": "lambda.amazonaws.com"}},
                    "Action": "sts:AssumeRole",
                }}],
            }},
        )
        aws.iam.RolePolicyAttachment(
            "lambda-basic-exec",
            role=lambda_role.name,
            policy_arn="arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
        )
        aws.iam.RolePolicyAttachment(
            "lambda-dynamodb-attach",
            role=lambda_role.name,
            policy_arn=aws.iam.Policy(
                "skaal-dynamodb-policy",
                name=f"{{stack_name}}-{app.name}-dynamodb",
                policy={{
                    "Version": "2012-10-17",
                    "Statement": [{{
                        "Effect": "Allow",
                        "Action": [
                            "dynamodb:GetItem",
                            "dynamodb:PutItem",
                            "dynamodb:DeleteItem",
                            "dynamodb:Scan",
                            "dynamodb:Query",
                        ],
                        "Resource": "*",
                    }}],
                }},
            ).arn,
        )
    """)

    # ── Lambda env vars ───────────────────────────────────────────────────────
    env_entries = "\n".join(
        f'    "SKAAL_TABLE_{cls.upper()}": {var}.name,'
        for cls, var in table_vars.items()
    )

    # ── Lambda function ───────────────────────────────────────────────────────
    w.blank()
    w.line("# ── Lambda Function " + "─" * 60)
    w.block(f"""\
        lambda_fn = aws.lambda_.Function(
            "skaal-lambda",
            name=f"{{stack_name}}-{app.name}",
            runtime="python3.11",
            handler="handler.handler",
            role=lambda_role.arn,
            code=pulumi.FileArchive("./lambda_package"),
            timeout=30,
            memory_size=256,
            environment=aws.lambda_.FunctionEnvironmentArgs(
                variables={{
{textwrap.indent(env_entries, "                ")}
                }},
            ),
        )
    """)

    # ── API Gateway ───────────────────────────────────────────────────────────
    w.blank()
    w.line("# ── HTTP API Gateway v2 " + "─" * 56)
    w.block(f"""\
        api = aws.apigatewayv2.Api(
            "skaal-api",
            name=f"{{stack_name}}-{app.name}-api",
            protocol_type="HTTP",
        )
        aws.lambda_.Permission(
            "api-invoke-lambda",
            action="lambda:InvokeFunction",
            function=lambda_fn.arn,
            principal="apigateway.amazonaws.com",
            source_arn=api.execution_arn.apply(lambda arn: f"{{arn}}/*/*"),
        )
        integration = aws.apigatewayv2.Integration(
            "lambda-integration",
            api_id=api.id,
            integration_type="AWS_PROXY",
            integration_uri=lambda_fn.invoke_arn,
            payload_format_version="2.0",
        )
        route = aws.apigatewayv2.Route(
            "default-route",
            api_id=api.id,
            route_key="$default",
            target=integration.id.apply(lambda i: f"integrations/{{i}}"),
        )
        stage = aws.apigatewayv2.Stage(
            "default-stage",
            api_id=api.id,
            name="$default",
            auto_deploy=True,
            opts=pulumi.ResourceOptions(depends_on=[route]),
        )
    """)

    # ── Exports ───────────────────────────────────────────────────────────────
    table_exports = "\n".join(
        f'    "{cls.lower()}": {var}.name,'
        for cls, var in table_vars.items()
    )

    w.blank()
    w.line("# ── Exports " + "─" * 68)
    w.line('pulumi.export("api_url", stage.invoke_url)')
    w.line('pulumi.export("lambda_arn", lambda_fn.arn)')
    w.block(f"""\
        pulumi.export("dynamodb_tables", {{
{textwrap.indent(table_exports, "    ")}
        }})
    """)

    return w.render()


# ── Public entry point ─────────────────────────────────────────────────────────

def generate_artifacts(
    app: Any,
    plan: "PlanFile",
    output_dir: Path,
    source_module: str,
    app_var: str = "app",
) -> list[Path]:
    """
    Generate Lambda + Pulumi deployment artifacts.

    Writes into *output_dir*:

    - ``handler.py``       — Lambda entry point (rendered from template)
    - ``requirements.txt`` — Python dependencies
    - ``pulumi/__main__.py`` — Pulumi infrastructure stack
    - ``pulumi/Pulumi.yaml`` — Pulumi project config (rendered from template)
    - ``README.md``        — Step-by-step deployment guide

    Args:
        app:           The Skaal App instance.
        plan:          The solved PlanFile (``plan.skaal.lock``).
        output_dir:    Directory to write files into (created if absent).
        source_module: Python module path, e.g. ``"examples.counter"``.
        app_var:       Variable name of the App in the module, e.g. ``"app"``.

    Returns:
        List of generated :class:`~pathlib.Path` objects.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    pulumi_dir = output_dir / "pulumi"
    pulumi_dir.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []
    backend_imports, backend_overrides = _build_wiring(plan)

    # ── handler.py ────────────────────────────────────────────────────────────
    handler_path = output_dir / "handler.py"
    handler_path.write_text(render(
        "aws/handler.py",
        app_name=app.name,
        source_module=source_module,
        app_var=app_var,
        backend_imports=backend_imports,
        backend_overrides=backend_overrides,
    ))
    generated.append(handler_path)

    # ── requirements.txt ─────────────────────────────────────────────────────
    requirements_path = output_dir / "requirements.txt"
    requirements_path.write_text("skaal[aws]\n")
    generated.append(requirements_path)

    # ── pulumi/__main__.py ────────────────────────────────────────────────────
    pulumi_main_path = pulumi_dir / "__main__.py"
    pulumi_main_path.write_text(_build_pulumi_main(app, plan))
    generated.append(pulumi_main_path)

    # ── pulumi/Pulumi.yaml ────────────────────────────────────────────────────
    pulumi_yaml_path = pulumi_dir / "Pulumi.yaml"
    pulumi_yaml_path.write_text(render("aws/Pulumi.yaml", app_name=app.name))
    generated.append(pulumi_yaml_path)

    # ── README.md ─────────────────────────────────────────────────────────────
    resource_lines = [
        f"- DynamoDB table for `{qname.split('.')[-1]}`"
        for qname, _ in plan.storage.items()
    ]
    resource_lines += [f"- Lambda function: `{app.name}`", "- HTTP API Gateway v2"]

    readme_path = output_dir / "README.md"
    readme_path.write_text(textwrap.dedent(f"""\
        # Deploy {app.name} to AWS (Lambda + DynamoDB)

        Generated by `skaal deploy`.

        ## Prerequisites

        - AWS credentials configured (`aws configure` or environment variables)
        - Pulumi CLI: `pip install pulumi pulumi-aws`

        ## Deploy

        ```bash
        # 1. Package the Lambda function
        pip install -r requirements.txt -t lambda_package/
        cp handler.py lambda_package/
        cp -r ../{source_module.split('.')[0]} lambda_package/

        # 2. Deploy infrastructure
        cd pulumi
        pip install pulumi pulumi-aws
        pulumi stack init dev
        pulumi config set aws:region us-east-1
        pulumi up
        ```

        ## Resources

        {chr(10).join(resource_lines)}
    """))
    generated.append(readme_path)

    return generated
