"""GCP Cloud Run artifact generator — thin orchestrator over deploy/templates/gcp/."""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Any

from skaal.deploy._render import _CodeWriter, render

if TYPE_CHECKING:
    from skaal.plan import PlanFile


# ── Per-backend metadata ───────────────────────────────────────────────────────

_BACKENDS: dict[str, dict[str, str]] = {
    "firestore": {
        "class": "FirestoreBackend",
        "import": "from skaal.backends.firestore_backend import FirestoreBackend",
        "env_prefix": "SKAAL_COLLECTION",
    },
    "cloud-sql-postgres": {
        "class": "PostgresBackend",
        "import": "from skaal.backends.postgres_backend import PostgresBackend",
        "env_prefix": "SKAAL_DB_DSN",
    },
    "memorystore-redis": {
        "class": "RedisBackend",
        "import": "from skaal.backends.redis_backend import RedisBackend",
        "env_prefix": "SKAAL_REDIS_URL",
    },
}

# Backends that need a VPC Connector in Cloud Run
_REQUIRES_VPC = {"cloud-sql-postgres", "memorystore-redis"}


def _backend_meta(backend_name: str) -> dict[str, str]:
    return _BACKENDS.get(backend_name, _BACKENDS["firestore"])


def _env_var(backend_name: str, class_name: str) -> str:
    return f"{_backend_meta(backend_name)['env_prefix']}_{class_name.upper()}"


def _constructor(backend_name: str, class_name: str, env_var: str) -> str:
    cls = _backend_meta(backend_name)["class"]
    if backend_name == "firestore":
        return f'{cls}(os.environ["{env_var}"])'
    if backend_name in ("cloud-sql-postgres", "memorystore-redis"):
        return f'{cls}(os.environ["{env_var}"], namespace="{class_name}")'
    return f'{cls}(os.environ["{env_var}"])'


# ── Wiring helpers (backend_imports / backend_overrides for templates) ─────────

def _build_wiring(plan: "PlanFile") -> tuple[str, str]:
    """
    Return (backend_imports, backend_overrides) template variables.

    backend_imports  — one import line per unique backend class used.
    backend_overrides — one ``"ClassName": BackendInstance(...)`` line per
                        storage class, indented to fit inside a dict literal
                        with 8-space indent.
    """
    seen_imports: set[str] = set()
    import_lines: list[str] = []
    override_lines: list[str] = []

    for qname, spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        meta = _backend_meta(spec.backend)
        env_var = _env_var(spec.backend, class_name)

        if meta["import"] not in seen_imports:
            seen_imports.add(meta["import"])
            import_lines.append(meta["import"])

        ctor = _constructor(spec.backend, class_name, env_var)
        override_lines.append(f'        "{class_name}": {ctor},')

    return "\n".join(import_lines), "\n".join(override_lines)


# ── Pulumi stack builder ───────────────────────────────────────────────────────

def _build_pulumi_main(app: Any, plan: "PlanFile", region: str) -> str:
    """Generate pulumi/__main__.py using _CodeWriter — no string-list hacks."""
    w = _CodeWriter()

    w.block(f"""\
        \"\"\"
        Pulumi stack generated by `skaal deploy`.
        App: {app.name}  Target: gcp-cloudrun
        Do not edit manually — regenerate with `skaal deploy`.
        \"\"\"
        import pulumi
        import pulumi_gcp as gcp

        config = pulumi.Config()
        stack_name = pulumi.get_stack()
        app_name = "{app.name}"
        region = config.get("gcp:region") or "{region}"
        project = config.require("gcp:project")
    """)

    w.blank()
    w.line("# ── Artifact Registry Repository " + "─" * 48)
    w.block(f"""\
        repo = gcp.artifactregistry.Repository(
            "skaal-repo",
            repository_id=f"{{stack_name}}-{app.name}",
            location=region,
            format="DOCKER",
        )
    """)

    # ── Per-storage resources ────────────────────────────────────────────────
    needs_vpc = any(spec.backend in _REQUIRES_VPC for _, spec in plan.storage.items())
    env_args: list[str] = []

    w.blank()
    w.line("# ── Storage Resources " + "─" * 59)

    for qname, spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        env_var = _env_var(spec.backend, class_name)
        w.blank()

        if spec.backend == "firestore":
            collection = f"{app.name}-{class_name.lower()}"
            w.line(f"# Firestore collection for {qname} (auto-created on first write)")
            w.line(f'firestore_{class_name.lower()} = "{collection}"')
            env_args.append(textwrap.dedent(f"""\
                gcp.cloudrun.ServiceTemplateSpecContainerEnvArgs(
                    name="{env_var}",
                    value=firestore_{class_name.lower()},
                ),"""))

        elif spec.backend == "cloud-sql-postgres":
            var = f"sql_{class_name.lower()}"
            w.block(f"""\
                {var} = gcp.sql.DatabaseInstance(
                    "{class_name.lower()}-sql",
                    database_version="POSTGRES_16",
                    region=region,
                    settings=gcp.sql.DatabaseInstanceSettingsArgs(
                        tier="db-f1-micro",
                        backup_configuration=gcp.sql.DatabaseInstanceSettingsBackupConfigurationArgs(
                            enabled=True,
                        ),
                    ),
                    deletion_protection=False,
                )
                gcp.sql.Database(
                    "{class_name.lower()}-db",
                    instance={var}.name,
                    name="{app.name}",
                )
            """)
            env_args.append(textwrap.dedent(f"""\
                gcp.cloudrun.ServiceTemplateSpecContainerEnvArgs(
                    name="{env_var}",
                    value={var}.connection_name.apply(
                        lambda cn: f"postgresql://skaal@localhost/{app.name}?host=/cloudsql/{{cn}}"
                    ),
                ),"""))

        elif spec.backend == "memorystore-redis":
            var = f"redis_{class_name.lower()}"
            w.block(f"""\
                {var} = gcp.redis.Instance(
                    "{class_name.lower()}-redis",
                    tier="BASIC",
                    memory_size_gb=1,
                    region=region,
                    redis_version="REDIS_7_0",
                )
            """)
            env_args.append(textwrap.dedent(f"""\
                gcp.cloudrun.ServiceTemplateSpecContainerEnvArgs(
                    name="{env_var}",
                    value={var}.host.apply(lambda h: f"redis://{{h}}:6379"),
                ),"""))

    # ── VPC connector (only when needed) ─────────────────────────────────────
    if needs_vpc:
        w.blank()
        w.line("# ── VPC Connector (required by Cloud SQL / Memorystore) " + "─" * 26)
        w.block(f"""\
            vpc_connector = gcp.vpcaccess.Connector(
                "skaal-vpc-connector",
                name=f"{{stack_name}}-connector",
                region=region,
                ip_cidr_range="10.8.0.0/28",
                network="default",
            )
            _annotations = {{
                "run.googleapis.com/vpc-access-connector": vpc_connector.name,
                "run.googleapis.com/vpc-access-egress": "private-ranges-only",
            }}
        """)
    else:
        w.blank()
        w.line("_annotations = {}")

    # ── Cloud Run Service ────────────────────────────────────────────────────
    env_block = "\n".join(
        textwrap.indent(arg, "                    ") for arg in env_args
    )
    w.blank()
    w.line("# ── Cloud Run Service " + "─" * 59)
    w.block(f"""\
        image = repo.name.apply(
            lambda r: f"{{region}}-docker.pkg.dev/{{project}}/{{r}}/{app.name}:latest"
        )

        cloud_run_service = gcp.cloudrun.Service(
            "skaal-cloudrun",
            name=f"{{stack_name}}-{app.name}",
            location=region,
            template=gcp.cloudrun.ServiceTemplateArgs(
                metadata=gcp.cloudrun.ServiceTemplateMetadataArgs(
                    annotations=_annotations,
                ),
                spec=gcp.cloudrun.ServiceTemplateSpecArgs(
                    containers=[gcp.cloudrun.ServiceTemplateSpecContainerArgs(
                        image=image,
                        envs=[
{env_block}
                        ],
                        resources=gcp.cloudrun.ServiceTemplateSpecContainerResourcesArgs(
                            limits={{"memory": "512Mi", "cpu": "1000m"}},
                        ),
                    )],
                ),
            ),
            traffics=[gcp.cloudrun.ServiceTrafficArgs(percent=100, latest_revision=True)],
        )

        # Allow public (unauthenticated) access — restrict via IAM if needed
        gcp.cloudrun.IamMember(
            "public-invoker",
            service=cloud_run_service.name,
            location=region,
            role="roles/run.invoker",
            member="allUsers",
        )
    """)

    # ── Exports ──────────────────────────────────────────────────────────────
    w.blank()
    w.line("# ── Exports " + "─" * 68)
    w.line('pulumi.export("service_url", cloud_run_service.statuses[0].url)')
    w.line('pulumi.export("image_repository", repo.name)')

    return w.render()


# ── Public entry point ─────────────────────────────────────────────────────────

def generate_artifacts(
    app: Any,
    plan: "PlanFile",
    output_dir: Path,
    source_module: str,
    app_var: str = "app",
    region: str = "us-central1",
) -> list[Path]:
    """
    Generate Cloud Run + Pulumi deployment artifacts.

    Writes into *output_dir*:

    - ``main.py``          — Cloud Run entry point (rendered from template)
    - ``Dockerfile``       — Container build spec (rendered from template)
    - ``requirements.txt`` — Python dependencies
    - ``pulumi/__main__.py`` — Pulumi infrastructure stack
    - ``pulumi/Pulumi.yaml`` — Pulumi project config (rendered from template)
    - ``README.md``        — Step-by-step deployment guide

    Args:
        app:           The Skaal App instance.
        plan:          The solved PlanFile (``plan.skaal.lock``).
        output_dir:    Directory to write files into (created if absent).
        source_module: Python module path, e.g. ``"examples.counter"``.
        app_var:       Variable name of the App in the module, e.g. ``"app"``.
        region:        GCP region, e.g. ``"us-central1"``.

    Returns:
        List of generated :class:`~pathlib.Path` objects.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    pulumi_dir = output_dir / "pulumi"
    pulumi_dir.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []
    backend_imports, backend_overrides = _build_wiring(plan)

    # ── main.py ──────────────────────────────────────────────────────────────
    main_path = output_dir / "main.py"
    main_path.write_text(render(
        "gcp/main.py",
        app_name=app.name,
        source_module=source_module,
        app_var=app_var,
        backend_imports=backend_imports,
        backend_overrides=backend_overrides,
    ))
    generated.append(main_path)

    # ── Dockerfile ───────────────────────────────────────────────────────────
    dockerfile_path = output_dir / "Dockerfile"
    dockerfile_path.write_text(render("gcp/Dockerfile"))
    generated.append(dockerfile_path)

    # ── requirements.txt ─────────────────────────────────────────────────────
    deps = ["skaal[gcp]", "uvicorn>=0.29"]
    for _, spec in plan.storage.items():
        if spec.backend == "cloud-sql-postgres":
            deps.append("cloud-sql-python-connector[asyncpg]>=1.9")
    requirements_path = output_dir / "requirements.txt"
    requirements_path.write_text("\n".join(dict.fromkeys(deps)) + "\n")
    generated.append(requirements_path)

    # ── pulumi/__main__.py ────────────────────────────────────────────────────
    pulumi_main_path = pulumi_dir / "__main__.py"
    pulumi_main_path.write_text(_build_pulumi_main(app, plan, region))
    generated.append(pulumi_main_path)

    # ── pulumi/Pulumi.yaml ────────────────────────────────────────────────────
    pulumi_yaml_path = pulumi_dir / "Pulumi.yaml"
    pulumi_yaml_path.write_text(render("gcp/Pulumi.yaml", app_name=app.name))
    generated.append(pulumi_yaml_path)

    # ── README.md ─────────────────────────────────────────────────────────────
    resource_lines = [
        f"- `{spec.backend}` backend for `{qname.split('.')[-1]}`"
        for qname, spec in plan.storage.items()
    ]
    resource_lines += ["- Cloud Run service", "- Artifact Registry repository"]

    readme_path = output_dir / "README.md"
    readme_path.write_text(textwrap.dedent(f"""\
        # Deploy {app.name} to GCP (Cloud Run)

        Generated by `skaal deploy`.

        ## Prerequisites

        - GCP project with billing enabled
        - `gcloud` CLI authenticated (`gcloud auth application-default login`)
        - Docker installed
        - Pulumi CLI: `pip install pulumi pulumi-gcp`

        ## Deploy

        ```bash
        PROJECT=your-gcp-project
        REGION={region}

        # 1. Provision infrastructure (creates Artifact Registry repo + storage)
        cd pulumi
        pip install pulumi pulumi-gcp
        pulumi stack init dev
        pulumi config set gcp:project $PROJECT
        pulumi config set gcp:region $REGION
        pulumi up

        # 2. Build and push the container image
        REPO=$(pulumi stack output image_repository)
        gcloud auth configure-docker $REGION-docker.pkg.dev
        docker build -t $REGION-docker.pkg.dev/$PROJECT/$REPO/{app.name}:latest ..
        docker push $REGION-docker.pkg.dev/$PROJECT/$REPO/{app.name}:latest

        # 3. Re-run `pulumi up` to deploy the image to Cloud Run
        pulumi up
        ```

        ## Resources

        {chr(10).join(resource_lines)}

        ## Notes

        - The Cloud Run service is public (unauthenticated). Add IAM bindings to restrict access.
        - Firestore collections are created automatically on first write.
        - Use Workload Identity or `GOOGLE_APPLICATION_CREDENTIALS` for auth in CI.
    """))
    generated.append(readme_path)

    return generated
